In [2]:
# Importacion de librerías a utilizar
import pandas as pd
import numpy as np
import matplotlib.pyplot as mt
import seaborn as sns
import scipy.special as special
from scipy.optimize import curve_fit
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
# Leer dataset a tratar
df = pd.read_csv("Datos_limpios_Berlin.csv")
df = df.drop("Unnamed: 0", axis=1)
df.head()

last_scraped                                               name  \
0   18/09/2024                  130 sqm with a view on Mauer Park   
1   18/09/2024                  light quiet beautiful 4 room flat   
2   18/09/2024                Super Apartment in Berlin/Kreuzberg   
3   18/09/2024  Rooftop apt w/ a view, 2 bedrooms/bathrooms, s...   
4   18/09/2024  Room w/ balcony and private bathroom in nice area   

                                         description  \
0  An apartment of 130 sqm right in the heart of ...   
1  We offer our 4 room apartment in Prenzlauer Be...   
2  Our fantastic typical Berlin-style apartment i...   
3  I am renting out my spacious, bright rooftop a...   
4  I´m offering a guest room with balcony in m...   

                               neighborhood_overview  \
0  Prenzlauer Berg is no doubt one of the most my...   
1  Prenzlauer Berg is no doubt one of the most my...   
2  Prenzlauer Berg is no doubt one of the most my...   
3  Kastanienalle, Oderberger Strasse, Hackescher ...   
4  The neighborhood "Prenzlauer Berg" is centrall...   

                                         picture_url  host_name  host_since  \
0  https://a0.muscache.com/pictures/miso/Hosting-...     Marine  14/11/2009   
1  https://a0.muscache.com/pictures/caa048ba-e297...      Katja  08/11/2010   
2  https://a0.muscache.com/pictures/176e2964-5ead...      Guidi  08/09/2010   
3  https://a0.muscache.com/pictures/1135114/9db3c...    Stephan  08/12/2010   
4  https://a0.muscache.com/pictures/miso/Hosting-...  Christian  07/12/2010   

                                          host_about  host_response_time  \
0  I'm french but I have been living in Berlin si...      within an hour   
1           Designer who likes discovering the world  within a few hours   
2  Hi , I am Elena and I am looking forward to ho...  within a few hours   
3  Ich mag schöne Dinge und Design. Wenn es ...        within a day   
4  Christian from Berlin\n\nHi, I´m a 52 years...  within a few hours   

  host_is_superhost  ... number_of_reviews_ltm number_of_reviews_l30d  \
0                 t  ...                  15.0                    0.0   
1                 t  ...                   7.0                    1.0   
2                 f  ...                   4.0                    0.0   
3                 f  ...                   0.0                    0.0   
4                 t  ...                  22.0                    0.3   

  review_scores_rating review_scores_accuracy review_scores_cleanliness  \
0                 4.93                   4.95                      4.90   
1                 4.84                   4.88                      4.79   
2                 4.70                   4.68                      4.65   
3                 4.75                   4.63                      4.50   
4                 4.95                   4.95                      4.92   

  review_scores_checkin review_scores_communication review_scores_location  \
0                  4.97                        4.94                   4.82   
1                  4.81                        4.91                   4.87   
2                  4.82                        4.82                   4.94   
3                  4.94                        4.63                   4.88   
4                  4.95                        4.92                   4.84   

  review_scores_value reviews_per_month  
0                4.76              0.80  
1                4.73              0.43  
2                4.47              0.20  
3                4.40              0.10  
4                4.77              0.73  

[5 rows x 50 columns]

**Primera variable: host_response_time**

In [4]:
df["host_response_time"].unique()

array(['within an hour', 'within a few hours', 'within a day',
       'a few days or more'], dtype=object)

In [5]:
# Se usará la variable objetivo host_response_time a predecir con ayuda de las siguientes variables independientes:
# host_acceptance_rate
# host_is_superhost
# number_of_reviews

# Sustituimos los valores de t y f por números: 1 y 0
df["host_is_superhost"] = df["host_is_superhost"].replace({"f":0,"t":1})
df["host_is_superhost"]

# Convertimos nuestra variable objetivo a números
encoder = LabelEncoder()
df["host_response_time"] = encoder.fit_transform(df["host_response_time"])
df["host_response_time"].unique()

# Convertimos 

C:\Users\DELL\AppData\Local\Temp\ipykernel_7448\646437218.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["host_is_superhost"] = df["host_is_superhost"].replace({"f":0,"t":1})


array([3, 2, 1, 0])

In [6]:
# Declaramos las variables dependientes e independientes para el análisis de regresión
vars_indep = df[["host_acceptance_rate","host_is_superhost","number_of_reviews"]]
var_dep = df["host_response_time"]

In [7]:
# Redefinimos las variables 
X = vars_indep
y = var_dep

In [8]:
# Dividimos los datos en conjunto de prueba y entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=None)

In [9]:
# Definimos la funcion de escalar
escalar = StandardScaler()

In [10]:
# Escalamos nuestros datos
x_train = escalar.fit_transform(X_train)
x_test = escalar.transform(X_test)

In [11]:
# Definimos la funcion del modelo a utilizar
from sklearn.linear_model import LogisticRegression
modelo = LogisticRegression()

In [12]:
# Entrenamos el modelo con los datos de entrenamiento
modelo.fit(X_train, y_train)

c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
# Realizamos las predicciones del modelo
y_pred = modelo.predict(X_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(3459,))

In [14]:
# visualizaremos la matriz de confusion para ver el endiemiento del modelo
from sklearn.metrics import confusion_matrix

matriz = confusion_matrix(y_test,y_pred)
print("Matriz de confusion")
print(matriz)

Matriz de confusion
[[   0  101    1    6]
 [   0 1541   14  143]
 [   0  192   15  165]
 [   0  542    6  733]]


In [15]:
# Calculamos la precisión del modelo para cada clase
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average=None)
print("Precisión del modelo")
print(precision)

Precisión del modelo
[0.         0.64856902 0.41666667 0.70009551]


c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [16]:
# Calculamos la precision del modelo en general
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="macro")
print("Precisión del modelo")
print(precision)

Precisión del modelo
0.4413328003048633


c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [17]:
# Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)

Exactitud del modelo
0.6617519514310495


In [18]:
# Calculamos la sensibilidad del modelo (verdaderos positivos)
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="macro")
print("Sensibilidad del modelo")
print(sensibilidad)

Sensibilidad del modelo
0.3800175181321087


**Segunda variable: host_is_superhost**

In [26]:
# Declaramos las variables dependientes e independentes
vars_indep = df[["host_response_rate", "host_acceptance_rate", "host_total_listings_count"]]
var_dep = df["host_is_superhost"]

In [27]:
# Redefinimos las variables
X = vars_indep
y = var_dep

In [28]:
# Dividimos los datos en conjunto de prueba y entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=None)

In [29]:
# Definimos la funcion de escalar
escalar = StandardScaler()

In [30]:
# Escalamos nuestros datos
x_train = escalar.fit_transform(X_train)
x_test = escalar.transform(X_test)

In [31]:
# Definimos la funcion del modelo a utilizar
from sklearn.linear_model import LogisticRegression
modelo = LogisticRegression()

In [32]:
# Entrenamos el modelo con los datos de entrenamiento
modelo.fit(X_train, y_train)

LogisticRegression()

In [33]:
# Realizamos las predicciones del modelo
y_pred = modelo.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(3459,))

In [34]:
# visualizaremos la matriz de confusion para ver el rendimiento del modelo
from sklearn.metrics import confusion_matrix

matriz = confusion_matrix(y_test,y_pred)
print("Matriz de confusion")
print(matriz)

Matriz de confusion
[[2643    2]
 [ 811    3]]


In [35]:
# Calculamos la precisión del modelo para cada clase
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average=None)
print("Precisión del modelo")
print(precision)

Precisión del modelo
[0.76519977 0.6       ]


In [36]:
# Calculamos la precision del modelo en general
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="macro")
print("Precisión del modelo")
print(precision)

Precisión del modelo
0.6825998841922409


In [37]:
# Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)

Exactitud del modelo
0.7649609713790113


In [38]:
# Calculamos la sensibilidad del modelo (verdaderos positivos)
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="macro")
print("Sensibilidad del modelo")
print(sensibilidad)

Sensibilidad del modelo
0.5014646800091034


**Tercera variable: beds**

In [40]:
# Convertimos la variable beds a numérica
encoder = LabelEncoder()
df["beds"] = encoder.fit_transform(df["beds"])
df["beds"].unique()

array([4, 1, 3, 2, 0])

In [44]:
# convertimos la variable room_type a numérica
encoder = LabelEncoder()
df["room_type"] = encoder.fit_transform(df["room_type"])
df["room_type"].unique()

array([0, 2, 3, 1])

In [46]:
# Declaramos las variables para la regresión
vars_indep = df[["accommodates", "bedrooms", "room_type"]]
var_dep = df["beds"]

In [47]:
# Redefinimos las variables
X = vars_indep
y = var_dep

In [48]:
# Dividimos los datos en conjunto de prueba y entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.3, random_state=None)

In [49]:
# Definimos la funcion de escalar
escalar = StandardScaler()

# Escalamos nuestros datos
x_train = escalar.fit_transform(X_train)
x_test = escalar.transform(X_test)

In [50]:
# Definimos la funcion del modelo a utilizar
from sklearn.linear_model import LogisticRegression
modelo = LogisticRegression()

In [51]:
# Entrenamos el modelo con los datos de entrenamiento
modelo.fit(X_train, y_train)

LogisticRegression()

In [52]:
# Realizamos las predicciones del modelo
y_pred = modelo.predict(X_test)
y_pred

array([3, 3, 1, ..., 3, 3, 3], shape=(8069,))

In [53]:
# visualizaremos la matriz de confusion para ver el rendimiento del modelo
from sklearn.metrics import confusion_matrix

matriz = confusion_matrix(y_test,y_pred)
print("Matriz de confusion")
print(matriz)

Matriz de confusion
[[   0   11    1   52    0]
 [   0  380    7 1916    0]
 [   0    0  215  403    0]
 [   0  425  145 3983    0]
 [   0    3  136  392    0]]


In [54]:
# Calculamos la precisión del modelo para cada clase
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average=None)
print("Precisión del modelo")
print(precision)

Precisión del modelo
[0.         0.46398046 0.4265873  0.59042395 0.        ]


c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [55]:
# Calculamos la precision del modelo en general
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred, average="macro")
print("Precisión del modelo")
print(precision)

Precisión del modelo
0.2961983441008048


c:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [56]:
# Calculamos la exactitud del modelo
from sklearn.metrics import accuracy_score

exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)

Exactitud del modelo
0.5673565497583344


In [57]:
# Calculamos la sensibilidad del modelo (verdaderos positivos)
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average="macro")
print("Sensibilidad del modelo")
print(sensibilidad)

Sensibilidad del modelo
0.27754128604621486
